# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'PlatformAPI' do
  pod 'AFNetworking', '~> 3.0'

  # Pods for PlatformAPI

end
